name: Relator

on:
  issues:
    types: [opened, labeled, reopened]
  pull_request_target:
    types: [opened, reopened]  # zizmor: ignore[dangerous-triggers]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  issues: read
  pull-requests: read

jobs:
  notify:
    name: "Send Telegram notification for new issue or opened pull request"
    if: github.actor != 'dependabot[bot]' && (github.event.action == 'opened' || github.event.action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification for new issue or opened pull request
        uses: reagento/relator@0942904cfa8775e115be93f3a1e39b365178d8f0  # v1.5.1
        with:
          tg-bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          tg-chat-id: ${{ secrets.TELEGRAM_TO }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          join-input-with-list: "1"

  notify-oss-board:
    name: "Send Telegram notification to OSS board"
    if: github.event_name == 'issues' && github.event.label.name == 'good first issue'
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification to OSS board
        uses: reagento/relator@0942904cfa8775e115be93f3a1e39b365178d8f0  # v1.5.1
        with:
          tg-bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          tg-chat-id: ${{ secrets.GFI_CHAT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          join-input-with-list: "1"
